### ISSUE TITLE
Failure in application startup

### ISSUE THREAD

**Issue by StoyanDimitrov** [dnGrep/dnGrep#1027]
The crash/hang occurred after manual update from zip archive from v4.0.189.0.

Here are the related `logevent` entries:
<details>

```xml
<logevent time="2024-01-11 10:00:00.8214" level="Error" logger="dnGREP.Common.GrepSettings">
  <message>Error converting settings key [Plugins] of type [System.Collections.Generic.List`1[dnGREP.Common.PluginConfiguration]] from value []</message>
  <exception>System.InvalidOperationException: Null default is not allowed for key Plugins
   at dnGREP.Common.GrepSettings.GetDefaultValue[T](String key) in C:\projects\dngrep\dnGREP.Common\GrepApplicationSettings.cs:line 1320
   at dnGREP.Common.GrepSettings.Get[T](String key) in C:\projects\dngrep\dnGREP.Common\GrepApplicationSettings.cs:line 986</exception>
</logevent>
<logevent time="2024-01-11 10:00:00.8645" level="Error" logger="dnGREP.WPF.App">
  <message>Failure in application startup</message>
  <exception>System.InvalidOperationException: Null default is not allowed for key Plugins
   at dnGREP.Common.GrepSettings.GetDefaultValue[T](String key) in C:\projects\dngrep\dnGREP.Common\GrepApplicationSettings.cs:line 1320
   at dnGREP.Common.GrepSettings.Get[T](String key) in C:\projects\dngrep\dnGREP.Common\GrepApplicationSettings.cs:line 1163
   at dnGREP.Common.GrepSettings.ConvertExtensionsToV3(String name, List`1 defaultExtensions) in C:\projects\dngrep\dnGREP.Common\GrepApplicationSettings.cs:line 1377
   at dnGREP.Common.GrepSettings.ConvertToV3() in C:\projects\dngrep\dnGREP.Common\GrepApplicationSettings.cs:line 611
   at dnGREP.Common.GrepSettings.Load(String path) in C:\projects\dngrep\dnGREP.Common\GrepApplicationSettings.cs:line 410
   at dnGREP.Common.GrepSettings.get_Instance() in C:\projects\dngrep\dnGREP.Common\GrepApplicationSettings.cs:line 369
   at dnGREP.WPF.App.Application_Startup(Object sender, StartupEventArgs e) in C:\projects\dngrep\dnGrep.WPF\App.xaml.cs:line 45</exception>
</logevent>
```

</details>

To recover after the crash I have to kill the app and rename/delete the `dnGREP.Settings.dat` file created from v4.0.189.0.
- dnGrep Version 4.1.4.0,
- Windows 10 x64
I can see that the old settings file have `<dictionary version="2"` and the newly created one `<dictionary version="3"`. Probably a migration gone awry.

**Comment by RichardS1** [comment]
I received an error message after updating to v4.1.4.0. In the Grep_Error_Log.xml file, the following was written after my attempted update:

```
<logevent time="2024-01-11 09:39:10.1017" level="Error" logger="dnGREP.Common.GrepSettings">
  <message>Error converting settings key [Plugins] of type [System.Collections.Generic.List`1[dnGREP.Common.PluginConfiguration]] from value []</message>
  <exception>System.InvalidOperationException: Null default is not allowed for key Plugins
   at dnGREP.Common.GrepSettings.GetDefaultValue[T](String key) in C:\projects\dngrep\dnGREP.Common\GrepApplicationSettings.cs:line 1320
   at dnGREP.Common.GrepSettings.Get[T](String key) in C:\projects\dngrep\dnGREP.Common\GrepApplicationSettings.cs:line 986</exception>
</logevent>
<logevent time="2024-01-11 09:39:10.2093" level="Error" logger="dnGREP.WPF.App">
  <message>Failure in application startup</message>
  <exception>System.InvalidOperationException: Null default is not allowed for key Plugins
   at dnGREP.Common.GrepSettings.GetDefaultValue[T](String key) in C:\projects\dngrep\dnGREP.Common\GrepApplicationSettings.cs:line 1320
   at dnGREP.Common.GrepSettings.Get[T](String key) in C:\projects\dngrep\dnGREP.Common\GrepApplicationSettings.cs:line 1163
   at dnGREP.Common.GrepSettings.ConvertExtensionsToV3(String name, List`1 defaultExtensions) in C:\projects\dngrep\dnGREP.Common\GrepApplicationSettings.cs:line 1377
   at dnGREP.Common.GrepSettings.ConvertToV3() in C:\projects\dngrep\dnGREP.Common\GrepApplicationSettings.cs:line 611
   at dnGREP.Common.GrepSettings.Load(String path) in C:\projects\dngrep\dnGREP.Common\GrepApplicationSettings.cs:line 410
   at dnGREP.Common.GrepSettings.get_Instance() in C:\projects\dngrep\dnGREP.Common\GrepApplicationSettings.cs:line 369
   at dnGREP.WPF.App.Application_Startup(Object sender, StartupEventArgs e) in C:\projects\dngrep\dnGrep.WPF\App.xaml.cs:line 45</exception>
</logevent>
```

I am using Windows 10 x64

**Comment by doug24** [comment]
Thanks for your reports - yes, I missed a couple of things updating the settings file.  I think I'll do another release today.

**Comment by RichardS1** [comment]
The fix works for me. Thanks!

**Comment by StoyanDimitrov** [comment]
Fixed, indeed.

I'll get around to clear the outstanding translations.
