### ISSUE TITLE
Something broke down in dnGrep

### ISSUE THREAD

**Issue by franqenstein** [dnGrep/dnGrep#1040]
Hello, having this error on open of dnGrep.

tell me please how to fix

![dnGrep - error](https://github.com/dnGrep/dnGrep/assets/49998268/2ad1f31f-a6b4-4fdf-b3cf-890b046de78e)

OS: Windows 7 PRO x64 - Build 7601:Service Pack 1
dnGrep version: dnGREP.4.1.7.x64.msi

Grep_Error_Log :
<logevent time="2024-01-29 15:35:06.8730" level="Error" logger="dnGREP.WPF.App">
  <message>Unhandled exception caught</message>
  <exception>System.DllNotFoundException: Unable to load DLL &apos;api-ms-win-shcore-scaling-l1-1-1.dll&apos; or one of its dependencies: The specified module could not be found. (0x8007007E)
   at dnGREP.Common.UI.Screen..ctor(HMONITOR monitor) in C:\projects\dngrep\dnGREP.Common.UI\Screen.cs:line 21
   at dnGREP.Common.UI.Screen.FromHandle(IntPtr handle) in C:\projects\dngrep\dnGREP.Common.UI\Screen.cs:line 83
   at dnGREP.Common.UI.Extensions.CenterWindow(Window window) in C:\projects\dngrep\dnGREP.Common.UI\Extensions.cs:line 270
   at dnGREP.WPF.MainForm.&lt;&gt;c__DisplayClass5_0.&lt;.ctor&gt;b__0(Object s, RoutedEventArgs e) in C:\projects\dngrep\dnGrep.WPF\Views\MainView.xaml.cs:line 88
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.Resize(ICompositionTarget resizedCompositionTarget)
   at System.Windows.Interop.HwndTarget.OnResize()
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean&amp; handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean&amp; handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)</exception>
</logevent>

**Comment by doug24** [comment]
dnGrep version 4.0 and higher requires Windows 10 or 11.  The last version supported on Windows 7 is [v3.2.330](https://github.com/dnGrep/dnGrep/releases/tag/v3.2.330.0)

**Comment by franqenstein** [comment]
my bad, sorry ((
