### ISSUE TITLE
Test tool broken, "Specified cast is not valid"

### ISSUE THREAD

**Issue by JVimes** [dnGrep/dnGrep#139]
_From [john.bu...@gmail.com](https://code.google.com/u/105739626209254255375/) on May 10, 2012 14:57:27_

What steps will reproduce the problem? 1. Try to use the Test tool What is the expected output? What do you see instead? It used to work, but now when I click "Search" in the Test window, I get an error telling me to check the event log, which shows the following:

<Error time="5/10/2012 14:50:55 PM">
  <Message>Specified cast is not valid.</Message>
  <Exception>
    <Message>Specified cast is not valid.</Message>
    <Source>dnGREP.Common</Source>
    <Stack>   at dnGREP.Common.GrepSettings.getDefaultValue[T](String key)
   at dnGREP.Common.GrepSettings.Get[T](String key)
   at dnGREP.WPF.TestPattern.btnSearch_Click(Object sender, RoutedEventArgs e)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean&amp; handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean&amp; handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean&amp; handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)</Stack>
    <Data key="System.Object" />
  </Exception>
</Error> What version of the product are you using? On what operating system? 2.6.3 x64, Windows 7 Please provide any additional information below.

**Attachment:** [2012-05-10_14h54_07.png](http://code.google.com/p/dngrep/issues/detail?id=136)

_Original issue: http://code.google.com/p/dngrep/issues/detail?id=136_

**Comment by doug24** [comment]
Still not fixed.  Importing images from web.archive.org
![2013-01-11_14h56_48](https://user-images.githubusercontent.com/17227248/59815845-c0f96980-92ce-11e9-8302-0dd5a5372fb4.png)
![2013-01-15_13h32_40](https://user-images.githubusercontent.com/17227248/59815853-c5258700-92ce-11e9-8170-212a168eb6b3.png)
