### ISSUE TITLE
<Message>Failed to search inside archive.</Message>

### ISSUE THREAD

**Issue by JVimes** [dnGrep/dnGrep#214]
_From [encr...@gmail.com](https://code.google.com/u/112550915769518699782/) on May 22, 2014 08:50:02_

Using 2.7.2 on 8.1 fully patched and updated.  Ran it and the event below was logged.  Unfortunately, I have no way of finding the problematic file using the information in the event.  The same general issue (not identifying the file path) applies when events are logged for symbolic links that can't be followed.

If an event complains about an issue with a file, please include the full path to that file in the event.

<Error time="5.21.2014 16:09:38 PM">
  <Message>Failed to search inside archive.</Message>
  <Exception>
    <Message>Invalid archive: open/read error! Is it encrypted and a wrong password was provided?
If your archive is an exotic one, it is possible that SevenZipSharp has no signature for its format and thus decided it is TAR by mistake.</Message>
    <Source>SevenZipSharp</Source>
    <Stack>   at SevenZip.SevenZipBase.ThrowException(CallbackBase handler, Exception[] e)
   at SevenZip.SevenZipExtractor.OpenArchive(IInStream archiveStream, ArchiveOpenCallback openCallback)
   at SevenZip.SevenZipExtractor.GetArchiveInfo(Boolean disposeStream)
   at SevenZip.SevenZipExtractor.InitArchiveFileData(Boolean disposeStream)
   at SevenZip.SevenZipExtractor.ExtractArchive(String directory)
   at dnGREP.Engines.Archive.GrepEngineArchive.Search(String file, String searchPattern, SearchType searchType, GrepSearchOption searchOptions, Encoding encoding)</Stack>
  </Exception>
</Error>

_Original issue: http://code.google.com/p/dngrep/issues/detail?id=211_

**Comment by doug24** [comment]
Fixed in 2.9.42 and later releases
