### ISSUE TITLE
Issue during installation doesnt install and tells to check event viewer 

### ISSUE THREAD

**Issue by samiullah321** [dnGrep/dnGrep#348]
![Untitled](https://user-images.githubusercontent.com/39356160/61243695-fecc9f00-a761-11e9-83f1-c2a6f86e6042.png)

Error	7/16/2019 12:30:41 AM	dnGREP	0	None
Log Name:      Application
Source:        dnGREP
Date:          7/16/2019 12:30:41 AM
Event ID:      0
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      DESKTOP-TTU9653
Description:
<Error time="7/16/2019 00:30:40.906">
  <Message>Configuration system failed to initialize</Message>
  <Exception>System.Configuration.ConfigurationErrorsException
   at System.Configuration.ConfigurationManager.PrepareConfigSystem()
   at System.Configuration.ConfigurationManager.RefreshSection(String sectionName)
   at System.Configuration.ClientSettingsStore.ReadSettings(String sectionName, Boolean isUserScoped)
   at System.Configuration.LocalFileSettingsProvider.GetPropertyValues(SettingsContext context, SettingsPropertyCollection properties)
   at System.Configuration.SettingsBase.GetPropertiesFromProvider(SettingsProvider provider)
   at System.Configuration.SettingsBase.GetPropertyValueByName(String propertyName)
   at System.Configuration.SettingsBase.get_Item(String propertyName)
   at System.Configuration.ApplicationSettingsBase.GetPropertyValue(String propertyName)
   at System.Configuration.ApplicationSettingsBase.get_Item(String propertyName)
   at dnGREP.WPF.Properties.Settings.get_MainFormExBounds()
   at dnGREP.WPF.MainForm..ctor(Boolean isVisible)
   at dnGREP.WPF.App.Application_Startup(Object sender, StartupEventArgs e)</Exception>
</Error>
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="dnGREP" />
    <EventID Qualifiers="0">0</EventID>
    <Level>2</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2019-07-15T19:30:41.010481300Z" />
    <EventRecordID>6264</EventRecordID>
    <Channel>Application</Channel>
    <Computer>DESKTOP-TTU9653</Computer>
    <Security />
  </System>
  <EventData>
    <Data>&lt;Error time="7/16/2019 00:30:40.906"&gt;
  &lt;Message&gt;Configuration system failed to initialize&lt;/Message&gt;
  &lt;Exception&gt;System.Configuration.ConfigurationErrorsException
   at System.Configuration.ConfigurationManager.PrepareConfigSystem()
   at System.Configuration.ConfigurationManager.RefreshSection(String sectionName)
   at System.Configuration.ClientSettingsStore.ReadSettings(String sectionName, Boolean isUserScoped)
   at System.Configuration.LocalFileSettingsProvider.GetPropertyValues(SettingsContext context, SettingsPropertyCollection properties)
   at System.Configuration.SettingsBase.GetPropertiesFromProvider(SettingsProvider provider)
   at System.Configuration.SettingsBase.GetPropertyValueByName(String propertyName)
   at System.Configuration.SettingsBase.get_Item(String propertyName)
   at System.Configuration.ApplicationSettingsBase.GetPropertyValue(String propertyName)
   at System.Configuration.ApplicationSettingsBase.get_Item(String propertyName)
   at dnGREP.WPF.Properties.Settings.get_MainFormExBounds()
   at dnGREP.WPF.MainForm..ctor(Boolean isVisible)
   at dnGREP.WPF.App.Application_Startup(Object sender, StartupEventArgs e)&lt;/Exception&gt;
&lt;/Error&gt;</Data>
  </EventData>
</Event>

-
Error	7/16/2019 12:31:26 AM	Application Hang	1002	(101)
Log Name:      Application
Source:        Application Hang
Date:          7/16/2019 12:31:26 AM
Event ID:      1002
Task Category: (101)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      DESKTOP-TTU9653
Description:
The program msiexec.exe version 5.0.18362.1 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel.
 Process ID: df4
 Start Time: 01d53b43a710a1bb
 Termination Time: 4294967295
 Application Path: C:\Windows\System32\msiexec.exe
 Report Id: a52539fb-b8a0-464f-8b98-e258b4c63ec4
 Faulting package full name: 
 Faulting package-relative application ID: 
 Hang type: Top level window is idle

Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Hang" />
    <EventID Qualifiers="0">1002</EventID>
    <Level>2</Level>
    <Task>101</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2019-07-15T19:31:26.155356100Z" />
    <EventRecordID>6268</EventRecordID>
    <Channel>Application</Channel>
    <Computer>DESKTOP-TTU9653</Computer>
    <Security />
  </System>
  <EventData>
    <Data>msiexec.exe</Data>
    <Data>5.0.18362.1</Data>
    <Data>df4</Data>
    <Data>01d53b43a710a1bb</Data>
    <Data>4294967295</Data>
    <Data>C:\Windows\System32\msiexec.exe</Data>
    <Data>a52539fb-b8a0-464f-8b98-e258b4c63ec4</Data>
    <Data>
    </Data>
    <Data>
    </Data>
    <Data>Top level window is idle</Data>
    <Binary>54006F00700020006C006500760065006C002000770069006E0064006F0077002000690073002000690064006C00650000000000</Binary>
  </EventData>
</Event>

Error	7/16/2019 12:31:27 AM	MsiInstaller	11722	None
Log Name:      Application
Source:        MsiInstaller
Date:          7/16/2019 12:31:27 AM
Event ID:      11722
Task Category: None
Level:         Error
Keywords:      Classic
User:          DESKTOP-TTU9653\Sami
Computer:      DESKTOP-TTU9653
Description:
Product: dnGREP 2.9.153 (x64) -- Error 1722. There is a problem with this Windows Installer package. A program run as part of the setup did not finish as expected. Contact your support personnel or package vendor. Action RunWarmUp, location: C:\Program Files\dnGREP\, command: "C:\Program Files\dnGREP\dnGREP.exe" /warmUp 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="MsiInstaller" />
    <EventID Qualifiers="0">11722</EventID>
    <Level>2</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2019-07-15T19:31:27.494988600Z" />
    <EventRecordID>6269</EventRecordID>
    <Channel>Application</Channel>
    <Computer>DESKTOP-TTU9653</Computer>
    <Security UserID="S-1-5-21-3407773545-3002127764-56573484-1001" />
  </System>
  <EventData>
    <Data>Product: dnGREP 2.9.153 (x64) -- Error 1722. There is a problem with this Windows Installer package. A program run as part of the setup did not finish as expected. Contact your support personnel or package vendor. Action RunWarmUp, location: C:\Program Files\dnGREP\, command: "C:\Program Files\dnGREP\dnGREP.exe" /warmUp </Data>
    <Data>(NULL)</Data>
    <Data>(NULL)</Data>
    <Data>(NULL)</Data>
    <Data>(NULL)</Data>
    <Data>(NULL)</Data>
    <Data>
    </Data>
    <Binary>7B42433330393436312D354133332D343235352D413538322D4641344136314238433331397D</Binary>
  </EventData>
</Event>

**Comment by doug24** [comment]
I suspect that something is corrupted in the user.config file when initializing the size and position of the main window.

I have two suggestions to try:

1) If there is an old copy of dnGREP.exe.config in C:\Program Files\dnGREP, then delete it, rename it or move it to another directory.

2) Also delete, rename or move existing copies of the "user.config" file found in %localappdata%\dnGrep
Looking in this directory:
C:\users\ username \AppData\Local\dnGrep
There should be a subdirectory named dnGREP.exe_Url_xxxx (with a random bunch of characters), and inside that directory, the dnGrep version number 2.9.143, 2.9.153, etc.   
The easiest method is to rename the AppData\Local\dnGrep folder so a new one will be created.  You can keep the old copies if you want to try restoring an old setting, but all that file is used for is to save and restore the last known window size and position.

Then, rerun the installer.
