### ISSUE TITLE
[Feature Request]: Report listing for search terms/phrases that are not present (low priority)

### ISSUE THREAD

**Issue by vatterspun** [dnGrep/dnGrep#434]
There are a number of different ways to address the issue below so I'll start with a use case.  I don't expect a lot of other people will need this functionality so I'm listing it as low priority.

---

**Use case**: As a Project Manager, I have some very long documents with a lot of terms and phrases that I sometimes search for with dnGREP.  However, some of those terms actually NEED to be in file and I need to make sure they weren't cut on the last edit by my client.  For example, it would be very embarrassing if a manual about traffic lights (at the minimum) didn't mention red, yellow, and green.

**Steps**

In the example below, I have a list of terms that I'm trying to check in a text file.  It's "potato chips" "corn" and "rice" so I put the word "OR" between each of those terms.

1. Search window `potato chips OR corn OR rice`

![image](https://user-images.githubusercontent.com/1289134/87261769-889e6d80-c485-11ea-83e7-0829fb518162.png)

2. Search Radio button is "text' and "Boolean operators" is checked 

3. Save Results to a report.

**Current behavior**

When I'm searching for something that doesn't appear in the document, naturally it just lists what's present, which is what most people would expect from their search program.  

**Requested behavior**

Right now if orange and yellow appear, it shows those in the report and if blue is not present it's excluded.  However, it would be great if -- in the detailed dnGREP report included terms that *aren't* present in addition to listing the ones that are.  The following output is standard for dnGREP, but the "Found no results for" is one way to show that something didn't show up in the document.

```
dnGrep Search Results

Search for: 'potato chips OR corn OR rice'
Using plaintext search
Boolean operators

Search in: C:\test
Paths that match: *.*

Found 2 matches on 2 lines in 1 files

C:\test\test.txt
has 2 matches on 2 lines:

     1:  potatos
	 
	 hey these potato chips are cooked

     2:  corn
	 
	 so we're out of corn 
	 
	 
Found no results for:

     1:  rice
```

**Comment by doug24** [comment]
I think this will require capturing the search pattern for each match that is found.  But I'm reluctant to annotate every match with the matching search pattern, or grouping results by the matching pattern.  There can be many matches in a file, and many matched files.

Here is a sample of the report output that I'm thinking of using - does this work for you?


```
dnGrep Search Results

Search for: 'event or action or callback'
Using plaintext search
Boolean operators

Search in: C:\Repos\testFiles\Test1\fileTypes
Paths that match: *.cs;*.php
No subfolders, No archives

Found 16 matches on 15 lines in 2 files

C:\Repos\testFiles\Test1\fileTypes\AppTheme.cs
has 7 matches on 6 lines:
Found matches for 'event'
Found no matches for 'action', 'callback'

    32:          public static AppTheme Instance { get; } = new AppTheme();
    33:  
    34:          public event EventHandler CurrentThemeChanged;
    35:  
    36:          private AppTheme() { }
    37:  
<snip>
--------------------------------------------------------------------------------

C:\Repos\testFiles\Test1\fileTypes\wp-settings.php
has 9 matches on 9 lines:
Found matches for 'action'
Found no matches for 'event', 'callback'

   164:  }
   165:  
   166:  do_action( 'muplugins_loaded' );
   167:  
   168:  if ( is_multisite() )
   169:  	ms_cookie_constants(  );
```

**Comment by doug24** [comment]
@vatterspun did you see my question on the example posted above?

**Comment by vatterspun** [comment]
> does this work for you?

This month has been overloaded so there was a delay on getting back to this topic.  But yes, that looks even better than what I pictured in my feature request.

**Comment by doug24** [comment]
Add this feature in v2.9.263

**Comment by vatterspun** [comment]
Fantastic update, thank you!  Here are the results from my test search in a document that had red, blue, green, but no yellow:

> C:\Users\Default\Desktop\Untitled 2.docx
> has 2 matches on 1 lines:
> Found matches for 'red', 'green'
> Found no matches for 'yellow'
> 
>      1:  red blue green 

Closing the case -- this is going to be super useful.  Thanks!

---

A few related notes:

* This doesn't seem to work with OR operations in regex checks like red|yellow|green
* Selecting "Copy Results" from the drop-down menu gives an error "Something broke down in the program. See event log for details" (on Win10x64)
* Save Results - Report has the data, but Save Results - Text Results does not seem to have the additional "no results" data, even though both outputs are text format.

**Comment by doug24** [comment]
About your notes:
1) That is expected: this was only written for the Boolean operation in dnGrep.
2) I haven't been able to reproduce this, maybe related to your results?  The log file is in the %appdata% folder: C:\Users\_username_\AppData\Roaming\dnGREP\logs if you want to post the actual error log.
3) That is also expected: Save Results is just a text output of the matches from the results window, and doesn't have any of the extra information such as the query run.

**Comment by vatterspun** [comment]
> Save Results is just a text output of the matches from the results window

Got it, thanks

> That is expected: this was only written for the Boolean operation in dnGrep.

Makes sense - I've been trying to do more in regex lately, but I can see why you're sticking with the term1 OR term2 search.

> I haven't been able to reproduce this, maybe related to your results?

Sure thing, here's the XML file:

<Error time="7/12/2020 20:44:34.530">
  <Message>{0}</Message>
  <Exception>System.IO.DirectoryNotFoundException
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at dnGREP.WPF.AppTheme.Initialize()</Exception>
  <Exception>
    <Message>Could not find a part of the path 'C:\Users\Core\AppData\Roaming\dnGrep\Sunset.xaml'.</Message>
    <Source>mscorlib</Source>
    <Stack>   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at dnGREP.WPF.AppTheme.Initialize()</Stack>
  </Exception>
</Error>
<Error time="7/12/2020 20:44:38.840">
  <Message>An error occurred while sending the request.</Message>
  <Exception>System.Net.Http.HttpRequestException
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at dnGREP.Common.PublishedVersionExtractor.&lt;QueryLatestVersion&gt;d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at dnGREP.WPF.MainViewModel.&lt;CheckVersion&gt;d__221.MoveNext()</Exception>
</Error>
<Error time="7/12/2020 20:44:54.285">
  <Message>The parameter value must be greater than zero.
Parameter name: emSize</Message>
  <Exception>System.ArgumentOutOfRangeException
   at System.Windows.Media.FormattedText.ValidateFontSize(Double emSize)
   at System.Windows.Media.FormattedText.InitFormattedText(String textToFormat, CultureInfo culture, FlowDirection flowDirection, Typeface typeface, Double emSize, Brush foreground, NumberSubstitution numberSubstitution, TextFormattingMode textFormattingMode, Double pixelsPerDip)
   at dnGREP.WPF.TextBoxWidthConverter.MeasureString(String candidate, Typeface typeface, Double fontSize, FrameworkElement control)
   at dnGREP.WPF.TextBoxWidthConverter.Convert(Object[] values, Type targetType, Object parameter, CultureInfo culture)
   at System.Windows.Data.MultiBindingExpression.TransferValue()
   at System.Windows.Data.MultiBindingExpression.Transfer()
   at System.Windows.Data.MultiBindingExpression.InvalidateChild(BindingExpressionBase bindingExpression)
   at System.Windows.Data.BindingExpression.TransferValue(Object newValue, Boolean isASubPropertyChange)
   at MS.Internal.Data.PropertyPathWorker.UpdateSourceValueState(Int32 k, ICollectionView collectionView, Object newValue, Boolean isASubPropertyChange)
   at MS.Internal.Data.ClrBindingWorker.OnSourcePropertyChanged(Object o, String propName)
   at System.Windows.WeakEventManager.ListenerList`1.DeliverEvent(Object sender, EventArgs e, Type managerType)
   at System.ComponentModel.PropertyChangedEventManager.OnPropertyChanged(Object sender, PropertyChangedEventArgs args)
   at System.ComponentModel.PropertyChangedEventHandler.Invoke(Object sender, PropertyChangedEventArgs e)
   at dnGREP.WPF.ViewModelBase.OnPropertyChanged(String propertyName)
   at dnGREP.WPF.MainViewModel.set_ApplicationFontFamily(String value)
   at dnGREP.WPF.MainViewModel.LoadSettings()
   at dnGREP.WPF.MainViewModel.ShowOptions()
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)</Exception>
</Error>
<Error time="7/12/2020 20:58:09.579">
  <Message>An error occurred while sending the request.</Message>
  <Exception>System.Net.Http.HttpRequestException
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at dnGREP.Common.PublishedVersionExtractor.&lt;QueryLatestVersion&gt;d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at dnGREP.WPF.MainViewModel.&lt;CheckVersion&gt;d__221.MoveNext()</Exception>
</Error>
<Error time="7/12/2020 21:00:13.619">
  <Message>An error occurred while sending the request.</Message>
  <Exception>System.Net.Http.HttpRequestException
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at dnGREP.Common.PublishedVersionExtractor.&lt;QueryLatestVersion&gt;d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at dnGREP.WPF.MainViewModel.&lt;CheckVersion&gt;d__221.MoveNext()</Exception>
</Error>
<Error time="7/12/2020 21:00:53.235">
  <Message>An error occurred while sending the request.</Message>
  <Exception>System.Net.Http.HttpRequestException
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at dnGREP.Common.PublishedVersionExtractor.&lt;QueryLatestVersion&gt;d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at dnGREP.WPF.MainViewModel.&lt;CheckVersion&gt;d__221.MoveNext()</Exception>
</Error>
<Error time="7/12/2020 21:09:25.733">
  <Message>OpenClipboard Failed (Exception from HRESULT: 0x800401D0 (CLIPBRD_E_CANT_OPEN))</Message>
  <Exception>System.Runtime.InteropServices.COMException
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at System.Windows.Clipboard.Flush()
   at System.Windows.Clipboard.CriticalSetDataObject(Object data, Boolean copy)
   at System.Windows.Clipboard.SetDataInternal(String format, Object data)
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)</Exception>
</Error>
<Error time="7/12/2020 21:16:22.359">
  <Message>OpenClipboard Failed (Exception from HRESULT: 0x800401D0 (CLIPBRD_E_CANT_OPEN))</Message>
  <Exception>System.Runtime.InteropServices.COMException
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at System.Windows.Clipboard.Flush()
   at System.Windows.Clipboard.CriticalSetDataObject(Object data, Boolean copy)
   at System.Windows.Clipboard.SetDataInternal(String format, Object data)
   at dnGREP.WPF.UserControls.ResultsTree.CopyGrepLines()
   at dnGREP.WPF.UserControls.ResultsTree.treeKeyDown(Object sender, KeyEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndKeyboardInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawKeyboardActions actions, Int32 scanCode, Boolean isExtendedKey, Boolean isSystemKey, Int32 virtualKey)
   at System.Windows.Interop.HwndKeyboardInputProvider.ProcessKeyAction(MSG&amp; msg, Boolean&amp; handled)
   at System.Windows.Interop.HwndSource.CriticalTranslateAccelerator(MSG&amp; msg, ModifierKeys modifiers)
   at System.Windows.Interop.HwndSource.OnPreprocessMessage(Object param)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)</Exception>
</Error>
<Error time="8/29/2020 01:57:47.299">
  <Message>(32) The process cannot access the file because it is being used by another process: [C:\Users\Core\Desktop\Untitled 2.docx]</Message>
  <Exception>System.IO.IOException
   at Alphaleonis.Win32.NativeError.ThrowException(UInt32 errorCode, String readPath, String writePath)
   at Alphaleonis.Win32.NativeError.ThrowException(Int32 errorCode, Nullable`1 isFolder, String readPath)
   at Alphaleonis.Win32.Filesystem.NativeMethods.CloseHandleAndPossiblyThrowException(SafeHandle handle, Int32 lastError, Nullable`1 isFolder, String path, Boolean throwException)
   at Alphaleonis.Win32.Filesystem.File.CreateFileCore(KernelTransaction transaction, Nullable`1 isFolder, String path, ExtendedFileAttributes attributes, FileSecurity fileSecurity, FileMode fileMode, FileSystemRights fileSystemRights, FileShare fileShare, Boolean checkPath, Boolean continueOnException, PathFormat pathFormat)
   at Alphaleonis.Win32.Filesystem.File.OpenCore(KernelTransaction transaction, String path, FileMode mode, FileSystemRights rights, FileShare share, ExtendedFileAttributes attributes, Nullable`1 bufferSize, FileSecurity security, PathFormat pathFormat)
   at dnGREP.Engines.OpenXml.GrepEngineOpenXml.Search(String fileName, String searchPattern, SearchType searchType, GrepSearchOption searchOptions, Encoding encoding)
   at dnGREP.Common.GrepCore.Search(String file, SearchType searchType, String searchPattern, GrepSearchOption searchOptions, Int32 codePage)</Exception>
</Error>
<Error time="8/29/2020 02:00:36.073">
  <Message>OpenClipboard Failed (Exception from HRESULT: 0x800401D0 (CLIPBRD_E_CANT_OPEN))</Message>
  <Exception>System.Runtime.InteropServices.COMException
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at System.Windows.Clipboard.Flush()
   at System.Windows.Clipboard.CriticalSetDataObject(Object data, Boolean copy)
   at System.Windows.Clipboard.SetDataInternal(String format, Object data)
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)</Exception>
</Error>
<Error time="8/29/2020 02:05:22.033">
  <Message>OpenClipboard Failed (Exception from HRESULT: 0x800401D0 (CLIPBRD_E_CANT_OPEN))</Message>
  <Exception>System.Runtime.InteropServices.COMException
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at System.Windows.Clipboard.Flush()
   at System.Windows.Clipboard.CriticalSetDataObject(Object data, Boolean copy)
   at System.Windows.Clipboard.SetDataInternal(String format, Object data)
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)</Exception>
</Error>
