### ISSUE TITLE
"Copy file names" option giving error message - But the filenames are getting copied without any issue.

### ISSUE THREAD

**Issue by tiniwings** [dnGrep/dnGrep#485]
Version:  v2.9.319.0 (beta) 64Bit
OS: Windows 10 Enterprise V 1803

Issue: "Copy file names" option giving  below error message, but the filenames are getting copied.

---------------------------
Error
---------------------------
Something broke down in the program. See event log for details.
---------------------------
OK   
---------------------------

**Comment by doug24** [comment]
There is a detailed error message in the file C:\Users\_username_\AppData\Roaming\dnGREP\logs\Grep_Error_Log.xml - can you copy it here?

**Comment by tiniwings** [comment]
<logevent time="2021-02-16 21:16:59.0206" level="Error" logger="dnGREP.WPF.App">
  <message>Unhandled exception caught</message>
  <exception>System.Runtime.InteropServices.COMException (0x800401D0): OpenClipboard Failed (Exception from HRESULT: 0x800401D0 (CLIPBRD_E_CANT_OPEN))
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at System.Windows.Clipboard.Flush()
   at System.Windows.Clipboard.CriticalSetDataObject(Object data, Boolean copy)
   at System.Windows.Clipboard.SetDataInternal(String format, Object data)
   at dnGREP.WPF.UserControls.ResultsTree.btnCopyFileNames_Click(Object sender, RoutedEventArgs e)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)</exception>
</logevent>

<logevent time="2021-02-16 21:17:12.4119" level="Error" logger="dnGREP.WPF.App">
  <message>Unhandled exception caught</message>
  <exception>System.Runtime.InteropServices.COMException (0x800401D0): OpenClipboard Failed (Exception from HRESULT: 0x800401D0 (CLIPBRD_E_CANT_OPEN))
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at System.Windows.Clipboard.Flush()
   at System.Windows.Clipboard.CriticalSetDataObject(Object data, Boolean copy)
   at System.Windows.Clipboard.SetDataInternal(String format, Object data)
   at dnGREP.WPF.UserControls.ResultsTree.btnCopyFileNames_Click(Object sender, RoutedEventArgs e)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)</exception>
</logevent>

**Comment by doug24** [comment]
OK, thanks.  I have not seen that happen, but googling the CLIPBRD_E_CANT_OPEN error indicates that it may be a conflict/race condition with another application that has the clipboard open, or is looking at the clipboard contents as soon as something new is added to the clipboard.  

Interesting that the filenames did get copied - that sounds a lot like this explanation:

> Internally that triggers two calls to the win32 api, one to set the data and one to flush it from your app so it's available after the app closes.

> I've seen several apps (some chrome plugin, and a download manager) that listen to the clipboard event. As soon as the first call hits, the app will open the clipboard to look into the data, and the second call to flush will fail.

**Comment by doug24** [comment]
I made changes in release 2.9.326 retry the "Copy" operation if the CLIPBRD_E_CANT_OPEN error is raised, and also try to show what application has the clipboard locked.

More details for those interested:

The Windows Clipboard is a resource shared by all applications, but if one is behaving badly, that will affect all the others.  I can't be certain that the included change will fix all issues, but I was able to produce similar behavior running a test program with an intentional bug) side by side with dnGrep.  

dnGrep is using the standard .NET API for copying text to the clipboard.  The Windows Clipboard APIs were written long ago when memory was scarce, so copying text to the clipboard is done in two steps: first to set that data is available on the clipboard (but doesn't actually copy the data anywhere), and the second to copy the data so it remains on the clipboard after the source application exits.  If you do the first step without the second, the data will only be transferred if another application requests it, and the source application is still running to supply it.  The .NET implementation retries each of the two steps up to 10 times before raising an error. 

I believe what you are seeing is that the first step succeeds, and Windows raises a notification that the clipboard data has changed.  Another application receives that notification and opens the clipboard to see what data is there, but does not close it again quickly.   Then when the .NET implementation tries the second step to copy the data to the clipboard, it finds that it is locked, retries and fails10 times, then raises the CLIPBRD_E_CANT_OPEN error.   

Note the data is "on" the clipboard, but not copied, so you can paste it elsewhere as long as dnGrep is still running to supply the data, or if the other application causes the data to be copied.

In the new code in dnGrep, if this error is raised, dnGrep tries to get the name of the application that has locked the clipboard.  Then, dnGrep falls back to a different .NET API to to do only the first step clipboard 'copy', without the second step.
