### ISSUE TITLE
"Detect file encoding" option doesn't play well with disconnected drives on Everything search

### ISSUE THREAD

**Issue by shawnkhall** [dnGrep/dnGrep#541]
When using an `Everything` search and searching for a **file name pattern only** with "search for" empty, an error is raised before completing the search if any matching result exists in a _disconnected source_. 

Disabling the option to `detect file encoding` allows the search to continue.

The error message is:

    <logevent time="2021-09-07 01:12:27.1023" level="Error" logger="dnGREP.WPF.MainViewModel">
      <message>Failed in search/replace</message>
      <exception>System.IO.IOException: (53) The network path was not found: [L:\example\matching.file]
       at Alphaleonis.Win32.NativeError.ThrowException(UInt32 errorCode, String readPath, String writePath)
       at Alphaleonis.Win32.NativeError.ThrowException(Int32 errorCode, Nullable`1 isFolder, String readPath)
       at Alphaleonis.Win32.Filesystem.NativeMethods.CloseHandleAndPossiblyThrowException(SafeHandle handle, Int32 lastError, Nullable`1 isFolder, String path, Boolean throwException)
       at Alphaleonis.Win32.Filesystem.File.CreateFileCore(KernelTransaction transaction, Nullable`1 isFolder, String path, ExtendedFileAttributes attributes, FileSecurity fileSecurity, FileMode fileMode, FileSystemRights fileSystemRights, FileShare fileShare, Boolean checkPath, Boolean continueOnException, PathFormat pathFormat)
       at Alphaleonis.Win32.Filesystem.File.OpenCore(KernelTransaction transaction, String path, FileMode mode, FileSystemRights rights, FileShare share, ExtendedFileAttributes attributes, Nullable`1 bufferSize, FileSecurity security, PathFormat pathFormat)
       at dnGREP.Common.Utils.GetFileEncoding(String srcFile)
       at dnGREP.Common.GrepCore.Search(IEnumerable`1 files, SearchType searchType, String searchPattern, GrepSearchOption searchOptions, Int32 codePage)
       at dnGREP.WPF.MainViewModel.DoSearchReplace(Object sender, DoWorkEventArgs e)</exception>
    </logevent>

I believe this is incorrect behavior and it should instead gracefully ignore or flag inaccessible files in the search results without raising an error. That is the behavior for searching **within** files on disconnected sources, so it makes sense that it should also be the behavior for the `detect file encoding` option.

**Comment by doug24** [comment]
Thanks, this is an easy fix to handle it the same way as when searching within files

**Comment by doug24** [comment]
Fixed in release v2.9.378.0
