### ISSUE TITLE
Reopen bookmarkswindow error

### ISSUE THREAD

**Issue by kumamiko** [dnGrep/dnGrep#865]
First, click the close button on the bookmarks window's titlebar to close window.
Then, click bookmarks menuitem on the MainWindow will show error.

Messages in log file.
````
<logevent time="2023-06-02 14:28:27.5607" level="Error" logger="dnGREP.WPF.App">
  <message>Unhandled exception caught</message>
  <exception>System.InvalidOperationException: Cannot set Visibility or call Show, ShowDialog, or WindowInteropHelper.EnsureHandle after a Window has closed.
   at System.Windows.Window.VerifyCanShow()
   at System.Windows.Window.Show()
   at dnGREP.WPF.MainViewModel.OpenBookmarksWindow()
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)</exception>
````
I guess the reason is MainWindowViewModel still hold the BookmarksWindow instance when I close it that way. And closed BookmarksWindow is not reusable？🤔

**Comment by doug24** [comment]
Thanks for the report!  The error occurs when using the X in the window titlebar or pressing alt+F4 to close the bookmarks window.  If you click the Close button at the bottom of the window or press the Esc key, it works without error.

Yes, the main window view model does hold an instance of the bookmarks window.  When the 'pin' button was added to the bookmarks window, the window was changed from a modal dialog to a top-level window.   It is expected that the bookmarks window is just hidden for reuse, and not closed/destroyed.  

I missed handling the titlebar X and alt+F4 close actions. It's a pretty easy fix to handle these, too.

**Comment by kumamiko** [comment]
Thanks.
