### ISSUE TITLE
Exception on replace

### ISSUE THREAD

**Issue by mnaoumov** [dnGrep/dnGrep#900]
When I use the following multiline Regex

**From**

```
\n(- .+)\n\n(- .+)
```

**To**

```

$1
$2
```

![image](https://github.com/dnGrep/dnGrep/assets/735878/f99f0a0d-1108-4758-9a33-6f893fbc1244)

```
System.InvalidOperationException: Cannot call this method on the Empty Rect.
   at System.Windows.Rect.Inflate(Double width, Double height)
   at dnGREP.WPF.ReplaceViewHighlighter.HighlightLine(TextView textView, DrawingContext drawingContext, VisualLine visLine, DocumentLine line) in C:\projects\dngrep\dnGrep.WPF\MVHelpers\ReplaceViewHighlighter.cs:line 130
   at dnGREP.WPF.ReplaceViewHighlighter.Draw(TextView textView, DrawingContext drawingContext) in C:\projects\dngrep\dnGrep.WPF\MVHelpers\ReplaceViewHighlighter.cs:line 60
   at ICSharpCode.AvalonEdit.Rendering.TextView.RenderBackground(DrawingContext drawingContext, KnownLayer layer) in C:\projects\dngrep\ICSharpCode.AvalonEdit\Rendering\TextView.cs:line 1295
   at ICSharpCode.AvalonEdit.Editing.SelectionLayer.OnRender(DrawingContext drawingContext) in C:\projects\dngrep\ICSharpCode.AvalonEdit\Editing\SelectionLayer.cs:line 68
   at System.Windows.UIElement.Arrange(Rect finalRect)
   at ICSharpCode.AvalonEdit.Rendering.TextView.ArrangeOverride(Size finalSize) in C:\projects\dngrep\ICSharpCode.AvalonEdit\Rendering\TextView.cs:line 1213
   at System.Windows.FrameworkElement.ArrangeCore(Rect finalRect)
   at System.Windows.UIElement.Arrange(Rect finalRect)
   at MS.Internal.Helper.ArrangeElementWithSingleChild(UIElement element, Size arrangeSize)
   at System.Windows.FrameworkElement.ArrangeCore(Rect finalRect)
   at System.Windows.UIElement.Arrange(Rect finalRect)
   at System.Windows.Controls.DockPanel.ArrangeOverride(Size arrangeSize)
   at System.Windows.FrameworkElement.ArrangeCore(Rect finalRect)
   at System.Windows.UIElement.Arrange(Rect finalRect)
   at System.Windows.Controls.Control.ArrangeOverride(Size arrangeBounds)
   at System.Windows.FrameworkElement.ArrangeCore(Rect finalRect)
   at System.Windows.UIElement.Arrange(Rect finalRect)
   at System.Windows.Controls.ScrollContentPresenter.ArrangeOverride(Size arrangeSize)
   at System.Windows.FrameworkElement.ArrangeCore(Rect finalRect)
   at System.Windows.UIElement.Arrange(Rect finalRect)
   at System.Windows.Controls.Grid.ArrangeOverride(Size arrangeSize)
   at System.Windows.FrameworkElement.ArrangeCore(Rect finalRect)
   at System.Windows.UIElement.Arrange(Rect finalRect)
   at System.Windows.Controls.Control.ArrangeOverride(Size arrangeBounds)
   at System.Windows.Controls.ScrollViewer.ArrangeOverride(Size arrangeSize)
   at System.Windows.FrameworkElement.ArrangeCore(Rect finalRect)
   at System.Windows.UIElement.Arrange(Rect finalRect)
   at System.Windows.Controls.Border.ArrangeOverride(Size finalSize)
   at System.Windows.FrameworkElement.ArrangeCore(Rect finalRect)
   at System.Windows.UIElement.Arrange(Rect finalRect)
   at System.Windows.Controls.Control.ArrangeOverride(Size arrangeBounds)
   at System.Windows.FrameworkElement.ArrangeCore(Rect finalRect)
   at System.Windows.UIElement.Arrange(Rect finalRect)
   at System.Windows.Controls.Border.ArrangeOverride(Size finalSize)
   at System.Windows.FrameworkElement.ArrangeCore(Rect finalRect)
   at System.Windows.UIElement.Arrange(Rect finalRect)
   at System.Windows.Controls.DockPanel.ArrangeOverride(Size arrangeSize)
   at System.Windows.FrameworkElement.ArrangeCore(Rect finalRect)
   at System.Windows.UIElement.Arrange(Rect finalRect)
   at System.Windows.Controls.Border.ArrangeOverride(Size finalSize)
   at System.Windows.FrameworkElement.ArrangeCore(Rect finalRect)
   at System.Windows.UIElement.Arrange(Rect finalRect)
   at MS.Internal.Helper.ArrangeElementWithSingleChild(UIElement element, Size arrangeSize)
   at System.Windows.FrameworkElement.ArrangeCore(Rect finalRect)
   at System.Windows.UIElement.Arrange(Rect finalRect)
   at System.Windows.Documents.AdornerDecorator.ArrangeOverride(Size finalSize)
   at System.Windows.FrameworkElement.ArrangeCore(Rect finalRect)
   at System.Windows.UIElement.Arrange(Rect finalRect)
   at System.Windows.Controls.Border.ArrangeOverride(Size finalSize)
   at System.Windows.FrameworkElement.ArrangeCore(Rect finalRect)
   at System.Windows.UIElement.Arrange(Rect finalRect)
   at System.Windows.Controls.DockPanel.ArrangeOverride(Size arrangeSize)
   at System.Windows.FrameworkElement.ArrangeCore(Rect finalRect)
   at System.Windows.UIElement.Arrange(Rect finalRect)
   at System.Windows.Controls.Border.ArrangeOverride(Size finalSize)
   at System.Windows.FrameworkElement.ArrangeCore(Rect finalRect)
   at System.Windows.UIElement.Arrange(Rect finalRect)
   at System.Windows.Window.ArrangeOverride(Size arrangeBounds)
   at System.Windows.FrameworkElement.ArrangeCore(Rect finalRect)
   at System.Windows.UIElement.Arrange(Rect finalRect)
   at System.Windows.ContextLayoutManager.UpdateLayout()
   at System.Windows.ContextLayoutManager.UpdateLayoutCallback(Object arg)
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by doug24** [comment]
I see your PR, thank-you!  
Can you post a sample test string that you are matching with this regex?

**Comment by doug24** [comment]
@mnaoumov - I also have not been able to reproduce this.

**Comment by mnaoumov** [comment]
@doug24 This issue comes and goes. I had it one time a few months ago. Today I had it persistently that's why I made my PR
