### ISSUE TITLE
Crash on startup after updating from ver 3.0.0 (x64) to 4.0.69 (x64)

### ISSUE THREAD

**Issue by bitseeker** [dnGrep/dnGrep#926]
Hi,
running Win10, dnGrap crashes with following error:
![image](https://github.com/dnGrep/dnGrep/assets/1962359/0df86909-8a23-4c62-ae7d-9c3ac81d4588)

the error log:
`<logevent time="2023-08-21 13:13:13.7026" level="Error" logger="dnGREP.Common.GrepSettings">
  <message>Error converting settings key [PreviewWindowWrap] of type [System.Boolean] from value [AAEAAAD/////AQAAAAAAAAAEAQAAAA5TeXN0ZW0uQm9vbGVhbgEAAAAHbV92YWx1ZQABAQs=]</message>
  <exception>System.FormatException: String &apos;AAEAAAD/////AQAAAAAAAAAEAQAAAA5TeXN0ZW0uQm9vbGVhbgEAAAAHbV92YWx1ZQABAQs=&apos; was not recognized as a valid Boolean.
   at System.Boolean.Parse(ReadOnlySpan`1 value)
   at System.String.System.IConvertible.ToBoolean(IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at dnGREP.Common.GrepSettings.Get[T](String key) in C:\projects\dngrep\dnGREP.Common\GrepApplicationSettings.cs:line 854</exception>
</logevent>
<logevent time="2023-08-21 13:13:13.7946" level="Error" logger="dnGREP.Common.GrepSettings">
  <message>Error converting settings key [StartDate] of type [System.Nullable`1[System.DateTime]] from value [AAEAAAD/////AQAAAAAAAAAEAQAAAA9TeXN0ZW0uRGF0ZVRpbWUCAAAABXRpY2tzCGRhdGVEYXRhAAAJEAAAAAAAAAAAAAAAAAAAAAAL]</message>
  <exception>System.InvalidOperationException: Null default is not allowed for key StartDate
   at dnGREP.Common.GrepSettings.GetDefaultValue[T](String key) in C:\projects\dngrep\dnGREP.Common\GrepApplicationSettings.cs:line 984
   at dnGREP.Common.GrepSettings.Get[T](String key) in C:\projects\dngrep\dnGREP.Common\GrepApplicationSettings.cs:line 813</exception>
</logevent>
<logevent time="2023-08-21 13:13:13.7946" level="Error" logger="dnGREP.WPF.App">
  <message>Failure in application startup</message>
  <exception>System.InvalidOperationException: Null default is not allowed for key StartDate
   at dnGREP.Common.GrepSettings.GetDefaultValue[T](String key) in C:\projects\dngrep\dnGREP.Common\GrepApplicationSettings.cs:line 984
   at dnGREP.Common.GrepSettings.Get[T](String key) in C:\projects\dngrep\dnGREP.Common\GrepApplicationSettings.cs:line 862
   at dnGREP.Common.GrepSettings.GetNullable[T](String key) in C:\projects\dngrep\dnGREP.Common\GrepApplicationSettings.cs:line 726
   at dnGREP.WPF.BaseMainViewModel.LoadSettings() in C:\projects\dngrep\dnGrep.WPF\ViewModels\BaseMainViewModel.cs:line 866
   at dnGREP.WPF.MainViewModel.LoadSettings() in C:\projects\dngrep\dnGrep.WPF\ViewModels\MainViewModel.cs:line 714
   at dnGREP.WPF.BaseMainViewModel..ctor() in C:\projects\dngrep\dnGrep.WPF\ViewModels\BaseMainViewModel.cs:line 36
   at dnGREP.WPF.MainViewModel..ctor() in C:\projects\dngrep\dnGrep.WPF\ViewModels\MainViewModel.cs:line 46
   at dnGREP.WPF.MainForm..ctor(Boolean isVisible) in C:\projects\dngrep\dnGrep.WPF\Views\MainView.xaml.cs:line 97
   at dnGREP.WPF.App.Application_Startup(Object sender, StartupEventArgs e) in C:\projects\dngrep\dnGrep.WPF\App.xaml.cs:line 63</exception>
</logevent>`

wondering why there is a path 'C:\projects\dngrep\...' in logfile, but there is definetly no such path on the system (showing all hidden files/folders).

What can i do to get dnGrap running?

thx Olli

**Comment by bitseeker** [comment]
Thanks Doug, changing about 9 lines did the trick.

**Comment by doug24** [comment]
Fixed in v4.0.115
